# Generated by Django 4.2.4 on 2023-09-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='наименование')),
                ('description', models.CharField(max_length=250, verbose_name='описание')),
                ('image', models.ImageField(upload_to='catalog/', verbose_name='изображение')),
                ('category', models.CharField(max_length=250, verbose_name='категория')),
                ('price', models.IntegerField(verbose_name='цена за покупку')),
                ('date_create', models.DateField(verbose_name='дата создания')),
                ('date_last_change', models.DateField(verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
